project:
  name: miyamotoapp2.5

services:
  - name: web
    start: streamlit run app.py
    env:
      - key: API_KEY
        value: "your_api_key_here"
    build:
      python_version: "3.10"
      requirements_path: requirements.txt 